name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build -Pgithub_actor=${{ secrets.GITHUB_ACTOR }} -Pgithub_token=${{ secrets.GITHUB_TOKEN }} -PossrhUsername=${{secrets.OSSRH_USERNAME}} -PossrhPassword=${{secrets.OSSRH_PASSWORD}}